### ISSUE TITLE
Page load hungs when using URL embeding

### ISSUE THREAD

**Issue by galmos** [dartiss/code-embed#49]
I'm using version 2.3.4 of the plugin and the page I'm trying to load hangs when using URL embedding codes.

Just loading an external page with:

{{https://www.example.com/page}}

But it does not work. I've tried to change these tags to check if there is some kind of conflict with the theme used but no way.

The theme I'm using right now is The 7

Thank you very much

**Comment by galmos** [comment]
I've found what's wrong about this issue:

First of all, there is an infinite loop in the _ce_quick_replace_ when the requested url gives an error. When there is an error inside the _ce_get_file_ function, the following line always gives the same startpos, because there is no offset and there hasn't been any replacement on $content.

`$start_pos = strpos( $content, $options['opening_ident'] . $search, 0 );`

This happens because there is an error reading the url to request, in this line:

`$url  = substr( $content, $start_pos + 1, $end_pos - $start_pos - 1 );`

The line should be as follows:
`$url  = substr( $content, $start_pos + strlen($options['opening_ident']), $end_pos - ($start_pos + strlen($options['opening_ident'])) );`

With those changes the problem is fixed.

Will try to make a PR in case anyone is interested

**Comment by dartiss** [comment]
Thanks @galmos - I'll get the change implemented.

**Comment by dartiss** [comment]
Fixed in 2.5
